### ISSUE TITLE
Spurious cursor movement after click

### ISSUE THREAD

**Issue by aarchiba** [numbas/numbas-extension-programming#19]
I and students have noticed a somewhat repeatable problem with code-entry boxes on assignments. The behaviour is:

1. Click somewhere in the box to begin typing there.
2. Begin typing.
3. After the first letter has appeared, the cursor leaps to the end of the entry box, where the rest of the characters appear. 

As you can imagine, this is infuriating. It does not happen every time, but it is quite frequent.

**Comment by chrismgraham** [comment]
Looked into this yesterday as it's been eating at me... not quite as far as proposing a solution, but here are some notes. 

I can replicate the above behaviour by selecting some text and then starting to type. 

I believe that what causes the cursor move is that, under those circumstances, the function setAnswerJSON is called (I'm not sure why setAnswerJSON is called when typing from a selection and not when just typing?), and these two lines in that function set the editor value, before dropping the cursor on the end:
```
editor.setValue(code);
editor.clearSelection();
```
I had thought it might be possible to get the cursor's position before those lines with
```
var currentPosition = editor.selection.getCursor();
```
and then correct after with
```
editor.gotoLine(currentPosition.row, currentPosition.column);
```
but sadly this does not seem to capture the position.

**Comment by christianp** [comment]
The fix for this was embarrassingly easy, once I'd spotted where the problem was: there's a race condition because the CodeEditor's `setAnswerJSON` function is async.
