### ISSUE TITLE
Restrict some libraries?

### ISSUE THREAD

**Issue by chigle** [numbas/numbas-extension-programming#2]
The following question https://numbas.mathcentre.ac.uk/question/114931/get-the-first-item-in-a-list/preview/ accepts the Python code that lists all the files in a virtual system. Although it is not a security risk, unintended codes might generate significant strain on the server. Could some libraries (like `glob,os,sys,platform,socket,uuid`) be restricted in the settings?

```
import glob
print(glob.glob('/**', recursive=True))
```

**Comment by christianp** [comment]
There's no server: all the code runs on the client, in a web worker. So I think the worst that a student could do would be to make their CPU very hot!
If you find a way of doing anything worse than that, I will of course investigate it.
