### ISSUE TITLE
Resource context IDs don't take account of loading of files when questions run standalone

### ISSUE THREAD

**Issue by chrismgraham** [numbas/numbas-extension-programming#35]
The recent commit to allow a context ID for resources works well in an exam, but seems that files aren't loaded when tested individually if the context ID is greater than 0 (example: https://numbas.mathcentre.ac.uk/question/155604/chris-s-copy-of-load-a-question-resource-file-in-python-or-r/)

**Comment by christianp** [comment]
That's why I said to use `question.number` as the context ID instead of hard coding it.

**Comment by chrismgraham** [comment]
Ahhh, got it!
