### ISSUE TITLE
Answers are marked as incorrect in R after an error

### ISSUE THREAD

**Issue by Lycanic** [numbas/numbas-extension-programming#37]
To recreate this issue:

In a R code question type, enter an invalid R command (for example, a random word which has no definition like 'banana') and submit.
Enter the correct answer to the question - no output is shown and the answer is marked incorrect.

This applies to all code bodies in the exam after an error is submitted, and refreshing the exam allows submission of new (uncached) answers.

**Comment by christianp** [comment]
Can you give me a link to an example? I just tried submitting `banana` (and got an error) and then `1` (which was marked correct, because the only marking test is set to always pass)

**Comment by Lycanic** [comment]
https://numbas.mathcentre.ac.uk/question/114723/r-as-a-calculator/ has this issue (verified on firefox and chrome on windows)

**Comment by christianp** [comment]
ha! I've just noticed that even though I called the _question_ "R", I didn't change my part to use R instead of Python. Doh!
