### ISSUE TITLE
Pyodide fatal error stops marking of subsequent parts

### ISSUE THREAD

**Issue by chrismgraham** [numbas/numbas-extension-programming#9]
Some Scipy functions seem to trigger an out of memory fatal error in Pyodide - the function tplquad in particular. It might be that some questions just need to be avoided, but if this does occur then it also stops all marking of future parts. Can something be done to catch this, stop the marking and restart Pyodide? A similar intervention would be useful in case a student introduces an infinite loop.

Minimal example here: https://numbas.mathcentre.ac.uk/question/127575/pyodide-fatal-error-issue/embed/?token=01c1bfe8-2434-4f11-9c4f-1d971785ed81

Error in JS console is 

```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.

RuntimeError: memory access out of bounds
```

Then on submitting another part...

```
Uncaught (in promise) Error: Pyodide already fatally failed and can no longer be used.
```

**Comment by christianp** [comment]
This might be fixed in the most recent pyodide version: I tried that code on https://pyodide.org/en/stable/console.html, which is currently using pyodide 0.21.0, and it worked OK (but gave a warning about reaching the maximum subdivisions).

For reference, here's the code:

```
from scipy import integrate
f = lambda z, y, x: x**2 + 2*x*y + y**2 + 2*x*z + z**2
integrate.tplquad(f, 1, 2, 2, 3, 0, 1) 
```

The extension currently loads pyodide 0.19.0. I'll see if we can switch to the latest version.

**Comment by christianp** [comment]
OK, the extension now uses 0.21.0, and that error doesn't happen.

It's now possible to run `loadPyodide` more than once in the same thread, so if an error like this happened again, we could recover by calling `loadPyodide` again. I can't make that error happen any more, so I haven't put in any code to do that yet.

**Comment by chrismgraham** [comment]
Great, thanks, I'll let you know if I encounter it again
